FROM nvcr.io/nvidia/isaac-sim:6.0.1

RUN /isaac-sim/python.sh -m pip install --no-cache-dir \
    cloudpickle==3.1.2 \
    farama-notifications==0.0.6 \
    flatdict==4.1.0 \
    gymnasium==1.2.0 \
    h5py==3.16.0 \
    prettytable==3.3.0 \
    wcwidth==0.2.13
